// Generated by CoffeeScript 1.3.3
(function() {

  KISSY.use("dom, node, anim, event, widget/dragswitch, widget/sslog", function(S, DOM, Node, Anim, Event, HoriDrag, SSlog) {
    var $;
    $ = KISSY.all;
    $("body").addClass("EntryList");
    new HoriDrag("#Main", {
      binds: [
        null, {
          moveEls: [],
          maxDistance: 200,
          validDistance: 20,
          passCallback: function() {
            $("#Main")[0].style.webkitTransform = "";
            return $("body")[0].className = "Main";
          },
          failCallback: null,
          checkvalid: function() {
            return $("body").hasClass("Menu");
          }
        }, null, {
          moveEls: [],
          maxDistance: DOM.viewportWidth(),
          validDistance: DOM.viewportWidth() / 2,
          passCallback: function() {
            $("#Main")[0].style.webkitTransform = "";
            return $("body")[0].className = "Menu";
          },
          failCallback: null,
          checkvalid: null
        }
      ]
    });
    return new HoriDrag(".entry-item", {
      binds: [
        null, null, null, {
          moveEls: [],
          maxDistance: 40,
          validDistance: 30,
          passCallback: function(ev) {},
          failCallback: null,
          checkvalid: null
        }
      ]
    });
  });

}).call(this);
