// Generated by CoffeeScript 1.3.3
(function() {

  KISSY.use("dom, node, anim, event, widget/dragswitch, widget/sslog, widget/draglist", function(S, DOM, Node, Anim, Event, DragSwitch, SSlog, DragList) {
    var $;
    $ = KISSY.all;
    $("body").addClass("EntryList");
    new DragSwitch("#Main", {
      binds: [
        null, {
          moveEls: [],
          maxDistance: 200,
          validDistance: 20,
          passCallback: function() {
            $("#Main")[0].style.webkitTransform = "";
            return $("body")[0].className = "Main";
          },
          failCallback: null,
          checkvalid: function() {
            return $("body").hasClass("Menu");
          }
        }, null, {
          moveEls: [],
          maxDistance: DOM.viewportWidth(),
          validDistance: DOM.viewportWidth() / 2,
          passCallback: function() {
            $("#Main")[0].style.webkitTransform = "";
            return $("body")[0].className = "Menu";
          },
          failCallback: null,
          checkvalid: null
        }
      ]
    });
    new DragSwitch(".entry-item", {
      binds: [
        null, null, null, {
          moveEls: [],
          maxDistance: 60,
          validDistance: 30,
          passCallback: function(ev) {
            $(ev.currentTarget).parent().addClass("entry-list-left");
            return ev.currentTarget.style.webkitTransform = "";
          },
          failCallback: null,
          checkvalid: null
        }
      ]
    });
    return $('#EntryList').on("touchstart", function() {
      return $(".entry-list-item").removeClass("entry-list-left");
    });
  });

}).call(this);
